version: '3.8'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: listapersonas
      MYSQL_ALLOW_CLEARTEXT_PASSWORD: 'true'